[workspace]

resolver = "2"

members = ["tests", "tain"]

default-members = ["tain"]

[workspace.dependencies]
log = "0.4"
dirs = "5.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
typed-builder = "0.20"
dotenvy = "0.15"
